CREATE DATABASE parkimine;
USE parkimine;
CREATE TABLE KASUTAJAD (
    ID INT NOT NULL AUTO_INCREMENT,
    KASUTAJA VARCHAR(100) NOT NULL,
    VÕTI VARCHAR(100) NOT NULL,
    ADMIN BOOL NOT NULL DEFAULT FALSE,
    PRIMARY KEY (ID)
);

INSERT INTO KASUTAJAD (KASUTAJA, VÕTI, ADMIN) VALUES ("admin",  MD5(CONCAT("admin", "admin")), TRUE);
INSERT INTO KASUTAJAD (KASUTAJA, VÕTI) VALUES ("parkija", MD5(CONCAT("parkija", "12345678")));

CREATE TABLE PARKIMINE (
    ID INT NOT NULL AUTO_INCREMENT,
    KASUTAJA_ID INT NOT NULL,
    AUTO_NR VARCHAR(6) NOT NULL,
    ALGUSAEG DATETIME NOT NULL,
    LÕPPAEG DATETIME NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(KASUTAJA_ID) REFERENCES KASUTAJAD (ID)
);
